firststart: True
sql:
  enable: false
  username: root
  password:
  url: mysql://localhost:3306/
cachesize: 1000
website:
  enabled: false
  https: false
  port: 443
  backlog: 100
safemode: true
lang:
  custom: false
  language: en-US
  playerindividuallang: true
